#!/bin/bash
testFiles=$(ls scanner_tests/test*)
for file in $testFiles
do
  scanner <$file >myOut 2>myErr
  echo $? >>myOut
  exscanner <$file >exOut 2>exErr
  echo $? >>exOut
  echo Test File $file
  echo stdout diffs:
  diff -Z myOut exOut
done